apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: hello-world
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: hello-world
  chart:
    git: git@github.com:st3il/hello-world
    path: flux/charts/hello-world/
    ref: master
  values:
    hello-nginx:
      image: saschariedel/hello-nginx:wvfszp6i
    hello-php:
      image: saschariedel/hello-php:wvfszp6i